tools/urls.py
from django.conf.urls import url


urlpatterns = []

from .views import index
urlpatterns += [
    url(r'^$', index.index),
    url(r'^login$', index.loginUser),
    url(r'^logout$', index.logoutUser),
    url(r'^logout/', index.logoutUser),
    url(r'^userHome$', index.userHome),
    url(r'^createUser$', index.createUser),
    url(r'^deleteUser$', index.deleteUser),
    url(r'^loginFailed$', index.loginFailed),
    url(r'^meandreTestCall$', index.meandreTestCall),
    url(r'^loginAsUser$', index.loginAsUser),
    url(r'^addTestTaskToDb$', index.addTestTaskToDb),
    url(r'^deleteMediaFile/$', index.deleteMediaFile),
]

from .views import project
urlpatterns += [
    url(r'^projects$', project.projects),
    url(r'^deleteProject/(?P<projectId>\d+)$', project.deleteProject),
    url(r'^startNewProject$', project.startNewProject),
    url(r'^addAudioToProject/(?P<audioFileID>\d+)$', project.addAudioToProject),
    url(r'^removeAudioFromProject/(?P<projectID>.*)/(?P<audioFileID>.*)$',project.removeAudioFromProject),
    url(r'^addUserToProject$', project.addUserToProject),
    url(r'^removeUserFromProject$', project.removeUserFromProject),
    url(r'^projectLibraryFiles/(?P<projectId>\d+)$', project.projectFiles), # keep temporarily for backward compatibility
    url(r'^projectFiles/(?P<projectId>\d+)$', project.projectFiles, name="projectFiles"),
    url(r'^projectNotes/(?P<projectId>\d+)$', project.projectNotes),
    url(r'^addMultipleAudioToProject/$', project.addMultipleAudioToProject),
    url(r'^AJAXRemoveAudioFromProject/$', project.AJAXRemoveAudioFromProject),
    url(r'^deleteMultipleProjects/$', project.deleteMultipleProjects),
]

from .views import audio
urlpatterns += [
    url(r'^enableAllAudioFiles/(?P<projectId>\d+)$',audio.enableAllAudioFiles),
    url(r'^disableAllAudioFiles/(?P<projectId>\d+)$',audio.disableAllAudioFiles),
    url(r'^enableAudioFile/(?P<projectId>\d+)/(?P<audioID>\d+)$',audio.enableAudioFile),
    url(r'^disableAudioFile/(?P<projectId>\d+)/(?P<audioID>\d+)$',audio.disableAudioFile),
    url(r'^deleteAudio/(?P<audioID>.*)$', audio.deleteAudio),
    url(r'^audioFiles$', audio.audioFiles),
    url(r'^getAudioInfo/(?P<tagID>.*)$',audio.getAudioInfo),
    url(r'^deleteUserAudioFiles$',audio.deleteUserAudioFiles),
    url(r'^importAudioFiles$', audio.importAudioFiles),
    url(r'^searchAudioFileNames[/]?$', audio.searchAudioFiles, {'responseFormat':'HTML'}),
]

from .views import biasManipulation
urlpatterns += [
    url(r'^setJobStatus/(?P<jobId>\d+)$', biasManipulation.setJobStatus),
    url(r'^setJobPriority/(?P<jobId>\d+)$', biasManipulation.setJobPriority),
    url(r'^stopQueuedChildTasks/(?P<parentJobId>\d+)$', biasManipulation.stopQueuedChildTasks),
    url(r'^queueStoppedChildTasks/(?P<parentJobId>\d+)$', biasManipulation.queueStoppedChildTasks),
    url(r'^stopQueuedTask/(?P<jobId>\d+)$', biasManipulation.stopQueuedTask),
    url(r'^queueStoppedTask/(?P<jobId>\d+)$',biasManipulation.queueStoppedTask),
    url(r'^searchQueueTasks/(?P<projectId>\d+)$', biasManipulation.searchQueueTasks),
    url(r'^manageJobs/(?P<projectId>\d+)$', biasManipulation.manageJobs),
    url(r'^randomWindowTagging/(?P<projectId>\d+)$', biasManipulation.randomWindowTagging),
    url(r'^getRandomWindowTasks/(?P<projectId>\d+)$', biasManipulation.getRandomWindowTasks),
]

from .views import catalog
urlpatterns += [
    url(r'^catalog/(?P<projectId>\d*)$', catalog.catalog),
]

from .views import expertAgreementClassification
urlpatterns += [
    url(r'^expertAgreementClassificationQueueRunner/(?P<projectId>\d+)$', expertAgreementClassification.expertAgreementClassificationQueueRunner),
]

from .views import exportLibraryMediaFileMetaData
urlpatterns += [
    url(r'^exportLibraryMediaFileMetaData/(?P<libraryId>[^/]+)$', exportLibraryMediaFileMetaData.exportLibraryMediaFileMetaData),
]

from .views import importLibraryUserMetaData
urlpatterns += [
    url(r'^importLibraryUserMetaData/(?P<libraryId>[^/]+)$', importLibraryUserMetaData.importLibraryUserMetaData),
]

from .views import importTagsFromCSV
urlpatterns += [
    url(r'^importTagsFromCSV/(?P<projectId>\d+)$',importTagsFromCSV.importTagsFromCSV),
]

from .views import library
urlpatterns += [
    url(r'^userLibraries$', library.userLibraries),
    url(r'^startNewLibrary$', library.startNewLibrary),
    url(r'^libraryFiles/(?P<libraryId>[^/]+)$', library.libraryFiles, name="libraryFiles"),
    url(r'^libraryAddSensorArray/(?P<libraryId>[^/]+)$', library.libraryAddSensorArray),
    url(r'^launchLibraryValidation/$', library.launchLibraryValidation),
    url(r'^libraryPermissions/(?P<libraryId>[^/]+)$', library.libraryPermissions),
    url(r'^deleteSensorArray/$', library.deleteSensorArray),
]

from .views import parameterInfo
urlpatterns += [
    url(r'^getInfo/(?P<infoType>.*)$',parameterInfo.getInfo),
]

from .views import projectPermissions
urlpatterns += [
    url(r'^projectPermissions/(?P<projectId>\d+)$', projectPermissions.projectPermissions),
]

from .views import reports
urlpatterns += [
    url(r'^createFileTagReport/(?P<projectId>\d+)$', reports.createFileTagReport),
]

from .views import sensor
urlpatterns += [
    url(r'^sensorArray/(?P<sensorArrayId>[^/]+)$', sensor.sensorArray),
    url(r'^updateSensorArrayLayout[/]?$', sensor.updateSensorArrayLayout),
]

from .views import supervisedTagDiscovery
urlpatterns += [
    url(r'^supervisedTagDiscoveryQueueRunner/(?P<projectId>\d+)$', supervisedTagDiscovery.supervisedTagDiscoveryQueueRunner),
    url(r'^supervisedTagDiscoveryQueueRunner/(?P<projectId>\d+)/fromJob/(?P<fromJob>\d+)$', supervisedTagDiscovery.supervisedTagDiscoveryQueueRunner),
    url(r'^supervisedTagDiscovery/(?P<projectId>\d+)$', supervisedTagDiscovery.supervisedTagDiscovery),
    url(r'^supervisedTagDiscovery/(?P<projectId>\d+)/fromJob/(?P<fromJob>\d+)$', supervisedTagDiscovery.supervisedTagDiscovery),
]

from .views import tagClass
urlpatterns += [
    url(r'^getTagClassAutoArray/(?P<projectId>\d+)$', tagClass.getTagClassAutoArray),
    url(r'^renameTagClass/(?P<tagClassId>\d+)$', tagClass.renameTagClass),
    url(r'^emptyTagClass/(?P<tagClassId>\d+)$', tagClass.emptyTagClass),
    url(r'^deleteTagClass/(?P<tagClassId>\d+)$', tagClass.deleteTagClass),
]

from .views import tag
urlpatterns += [
    url(r'^getTagInfo/(?P<tagID>.*)$', tag.getTagInfo),
    url(r'^viewTag/(?P<tagID>.*)$', tag.viewTag),
    url(r'^viewParentTag/(?P<tagID>.*)$', tag.viewParentTag),
    url(r'^deleteTag/(?P<tagID>.*)$', tag.deleteTag),
    url(r'^acceptTag/(?P<tagID>.*)$', tag.acceptTag),
    url(r'^getTagsInAudioSegment/(?P<audioID>.*)/(?P<startTime>.*)/(?P<endTime>.*)/(?P<minFrequency>.*)/(?P<maxFrequency>.*)$', tag.getTagsInAudioSegment),
    url(r'^createUserTag/(?P<projectID>.*)/(?P<mediaFileId>.*)$', tag.createUserTag),
    url(r'^navigateTags/(?P<projectID>\d+)/(?P<audioID>\d+)$', tag.navigateTags),
    url(r'^createUserTag/(?P<projectId>\d+)$', tag.newCreateUserTag),
    url(r'^adjustTag/(?P<tagId>\d+)$', tag.adjustTag),
    url(r'^deleteTags/(?P<projectId>\d+)$', tag.deleteTags),
    url(r'^getDeleteTagCount/(?P<projectId>\d+)$', tag.getDeleteTagCount),
]

from .views import tagSet
urlpatterns += [
    url(r'^deleteTagSet/(?P<tagSetId>\d+)$', tagSet.deleteTagSet),
    url(r'^tagSets$', tagSet.tagSets),
    url(r'^projectTagSets/(?P<projectId>\d+)$', tagSet.projectTagSets),
    url(r'^startNewTagSet/(?P<projectId>\d+)$', tagSet.startNewTagSet),
    url(r'^getProjectTagSetsInfo/(?P<projectId>\d+)$', tagSet.getProjectTagSetsInfo),
    url(r'^viewTagSet/(?P<tagSetId>.*)$', tagSet.viewTagSet),
]

from .views import tempFunctions
urlpatterns += [
    url(r'^compareExpertTagging/(?P<compareTagSetId>\d+)$', tempFunctions.compareExpertTagging),
]

from .views import transcriptCreation
urlpatterns += [
    url(r'^createTranscriptForTagSet/(?P<projectId>\d+)$', transcriptCreation.createTranscriptForTagSet),
]

from .views import pitchTraceCsv
urlpatterns += [
    url(r'^createPitchTraceCsv/(?P<projectId>\d+)/(?P<mediaFileId>\d+)$', pitchTraceCsv.createPitchTraceCsv),
]

from .views import unsupervisedTagDiscovery
urlpatterns += [
    url(r'^unsupervisedTagDiscoveryQueueRunner/(?P<projectId>\d+)$', unsupervisedTagDiscovery.unsupervisedTagDiscoveryQueueRunner),
    url(r'^unsupervisedTagDiscovery/(?P<projectId>\d+)$', unsupervisedTagDiscovery.unsupervisedTagDiscovery),
]

from .views import upload
urlpatterns += [
    url(r'^uploadAudioFile$', upload.uploadAudioFile),
    url(r'^uploadAudioFile2$', upload.uploadAudioFile2),
]

from .views import userPermissions
urlpatterns += [
    url(r'^userGroups/$', userPermissions.userGroupsView),
    url(r'^arloUserGroup/(?P<arloUserGroupId>\d+)$', userPermissions.arloUserGroup)
]

from .views import userSettings
urlpatterns += [
    url(r'^userSettings$', userSettings.userSettings),
    url(r'^viewSettings/(?P<settingsName>.*)$', userSettings.viewSettings),
    url(r'^deleteSettings/(?P<settingsName>.*)$', userSettings.deleteSettings),
]

from .views import viewJob
urlpatterns += [
    url(r'^viewJob/(?P<jobID>\d+)$', viewJob.viewJob, name='viewJob'),
]

from .views import viewMetaData
urlpatterns += [
    url(r'^guessTimeFromName/(?P<audioID>[^/]+)$', viewMetaData.guessTimeFromName),
    url(r'^viewMetadata/(?P<audioID>[^/]+)$', viewMetaData.viewMetadata),
]

from .views import visualizeMultiProjectFile
urlpatterns += [
    url(r'^visualizeMultiProjectFile/(?P<projectId>\d+)$', visualizeMultiProjectFile.visualizeMultiProjectFile),
    url(r'^createAudioSpectra/(?P<audioFileId>[^/]+)$', visualizeMultiProjectFile.newCreateAudioSpectra),
]

from .views import visualizeProjectFile
urlpatterns += [
    url(r'^visualizeProjectFile/(?P<projectId>\d+)/(?P<audioID>\d+)/$', visualizeProjectFile.visualizeProjectFile),
    url(r'^visualizeProjectFileTags/(?P<projectId>\d+)/(?P<audioID>\d+)/(?P<tagSetID>\d+)/$', visualizeProjectFile.visualizeProjectFileTags),

urls.py
from django.conf.urls import *
from django.contrib import admin, auth
from django.contrib.auth import views as auth_views
from django.views import static
from django.conf import settings
import rest_framework.authtoken.views as rest_views

from tools import urls as tools_urls
from tools.views import index
from poetrytagging import urls as poetrytagging_urls
from metatagging import urls as metatagging_urls
from api import urls as api_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/login/$', auth_views.login),

    url(r'^tools/', include(tools_urls)),
    url(r'^poetrytagging/', include(poetrytagging_urls)),
    url(r'^metatagging/', include(metatagging_urls)),

    url(r'^$', index.index),

    url(r'^api/', include(api_urls)),
    url(r'^api-token-auth/', rest_views.obtain_auth_token),

    url(r'^changePassword$', auth.views.password_change, name='password_change'),
    url(r'^changePasswordDone$', auth.views.password_change_done, name='password_change_done'),
]

if settings.USE_STATIC_SERVE:
  urlpatterns += [
      url(r'^site_media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes':True}),
      url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes':True}),
  ]

metatagging/views/chooseProject.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotAllowed
from django.shortcuts import render, redirect
from django import forms
from django.conf import settings

from tools.models import Project


class ChooseProjectForm(forms.Form):
  project = forms.ModelChoiceField(Project.objects.none(), required=True)

## Select a Project to use for the Poetry Tagging
# @param request The Django HTTP request object.
# @return Django HTTP response object.

@login_required
def chooseProject(request):
  user = request.user

  if request.method == 'GET':
    form = ChooseProjectForm()
    form.fields['project'] = forms.ModelChoiceField(Project.objects.getUserProjects(user).order_by('name'), required=True)

    return render(request, 'chooseProject.html', {
      'apacheRoot':settings.APACHE_ROOT,
      'user':user,
      'form':form,
      })


  elif request.method == 'POST':
    form = ChooseProjectForm(request.POST)
    form.fields['project'] = forms.ModelChoiceField(Project.objects.getUserProjects(user).order_by('name'), required=True)

    if not form.is_valid():
      return render(request, 'chooseProject.html', {
        'apacheRoot':settings.APACHE_ROOT,
        'user':user,
        'form':form,
        })

    data = form.cleaned_data
    project = data['project']

    return redirect('chooseTagSet', projectId=project.id)

  else:
    return HttpResponseNotAllowed(['GET', 'POST'])

tools/views/create.py
import logging

from tools.models import TagClass


class EmptyStringException(Exception):
  def __str__(self):
    return "Cannot create object with empty string as it's name!"




## Add a new TagClass to a Project.
# @param user User Object
# @param project The Project Object to which the TagClass belongs
# @param className The Class Name of the new TagClass
# @param displayName The Display Name of the new TagClass
# @return The new TagClass object (None if failure)

def createTagClass(user, project, className, displayName):
  logging.info("Creating tag class")
  if className == '':
    raise EmptyStringException
  try:
    tagClass = TagClass.objects.get(project=project,className=className)
    logging.warning('TagClass with name already exists!')
    return None
  except:
    #because display name is optional, must do this
    if displayName == '':
      dn = className
    else:
      dn = displayName

    tagClass = TagClass(user=user,project=project,className=className,displayName=dn)
    tagClass.save()
    return tagClass

tools/views/importLibraryUserMetaData.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponseForbidden

from tools.models import Library
from .userPermissions import ARLO_PERMS


## Display the page to allow users to bulk-import MediaFileUserMetaData Entries.
#
# The bulk of this work takes place in the JavaScript. Just display the tool here.
# @param request The Django HTTP request object
# @param libraryId The database ID of the Library to which we are importing.
# @return Django HTTP response object

@login_required
def importLibraryUserMetaData(request, libraryId):
  user = request.user
  library = Library.objects.get(id=libraryId)

  # Check user permissions
  if not library.userHasPermissions(user, ARLO_PERMS.WRITE):
    return HttpResponseForbidden("Forbidden - You do not have write access to this Library.")

  return render(request, 'tools/importLibraryUserMetaData.html',
                           {'user': user,
                            'library':library,
                            })

tools/views/importTagsFromCSV.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponseForbidden
from django import forms

from tools.models import Project, TagSet, TagClass
from .userPermissions import ARLO_PERMS


class ImportTagForm(forms.Form):
  tagSet   = forms.ModelChoiceField(TagSet.objects.none())
  tagClass = forms.ModelChoiceField(TagClass.objects.none())


##
#
# The bulk of this work takes place in the JavaScript. Just display the tool here.
# @param request The Django HTTP request object
# @param projectId The database ID of the Project to which we are importing.
# @return Django HTTP response object

@login_required
def importTagsFromCSV(request, projectId):
  user = request.user
  project = Project.objects.get(id=projectId)

  # Check user permissions
  if not project.userHasPermissions(user, ARLO_PERMS.WRITE):
    return HttpResponseForbidden("Forbidden - You do not have write access to this Project.")

  form = ImportTagForm()
  form.fields['tagSet']   = forms.ModelChoiceField(project.getTagSets(include_hidden=False))
  form.fields['tagClass'] = forms.ModelChoiceField(project.getTagClasses())

  return render(request, 'tools/importTagsFromCSV.html',
                           {'user': user,
                            'project': project,
                            'form': form,
                            })

templates/tools/audioFiles.html
{% extends "tools/base.html" %}

{% block javascript%}

	{% load staticfiles %}

	<link rel="stylesheet" href="{% static 'tools/css/arlo.css' %}" type="text/css" />

	<script src="{% static 'third-party/jquery-form/jquery.form.js' %}" type="text/javascript"></script>
	<script src="{% static 'third-party/sorttable/sorttable.js' %}" type="text/javascript"></script>
	<script src="{% static 'tools/js/arlo.js' %}" type="text/javascript"></script>

<script type="text/javascript">
<!--

	var urlPrefix = "{{ArloUrlPrefix}}";

	function searchFormCallback(json) {
		if (json.searchString.length) {
			var sFileCount = "Searching Media Files... (showing " + json.filesReturned + " of " + json.totalFiles + " found)";
		} else {
			var sFileCount = "Media Files (" + json.filesReturned + " of " + json.totalFiles + " shown)";
		}

		$("#fileCount").prop('innerHTML', sFileCount);

		// empty table except for header row
		var otable=document.getElementById("filesTable");
		while(otable.rows.length>1) 
			otable.deleteRow(otable.rows.length-1); 

		// add results to table
		$.each(json.filesDict, function(index) {
			var id = json.filesDict[index].mediaID;
			var row = '<tr>';
			row += '<td><a href=' + urlPrefix + '/tools/visualizeAudio/' + id + '>Visualize</a></td>';
			row += '<td><a href=' + urlPrefix + '/tools/viewMetadata/' + id + '>Edit Meta</a></td>';
			row += '<td><a class ="delete" href=' + urlPrefix + '/tools/deleteAudio/' + id + '>Delete</a></td>';
			row += '<td>' + json.filesDict[index].startTime + '</td>';
			row += '<td>' + json.filesDict[index].alias + '</td>';
			row += '<td>' + json.filesDict[index].sensorName + '</td>';
			row += '<td>' + json.filesDict[index].durationInSeconds + '</td>';
			row += '</tr>';

			$(row).appendTo("#filesTable");
		});

		// setup a 'delete confirmation' on the links
		// since these are created after page load, they aren't picked up by the Django default 'delete' confirmation.
		$(".delete").click(function(event){
			var x = window.confirm("Are you sure you want to delete this?");
			if(!x) {
				event.preventDefault();
			};
		});
	};

	function searchFiles() {
		$("#fileCount").prop('innerHTML', 'Loading Files... <img src="{% static 'tools/img/loading.gif' %}" width="20px" height="20px"/>');

		$("#searchForm").ajaxSubmit({
			url:'{{ArloUrlPrefix}}/tools/searchAudioFileNames',
			dataType:'json',
			error:function() {ARLOLogError("Error Searching Files");},
			success:searchFormCallback 
		});
	};


	$(document).ready(function() {
		ARLOInit();
		searchFiles();
	});

-->
</script>



{% endblock javascript %}


{% block content %}

<H1>Media File Page</H1><HR>

<H2><a href="{{ArloUrlPrefix}}/tools/uploadAudioFile">Upload Media File</a></H2>
<H2><a href="{{ArloUrlPrefix}}/tools/uploadAudioFile2">Upload and Convert</a> (supports MP3)</H2>

{%comment%}
<del><H2><!--<a href="{{ArloUrlPrefix}}/tools/deleteUserAudioFiles" class="delete">-->(warning: Delete All Media Files)<!--</a>--></H3></del>
{%endcomment%}
<hr />
<H2 id="fileCount">Existing Media Files</H2>


  <!-- Heads up using jQuery ajaxJorm you must specify method for the Form -->
  <!-- alse SubmitFormOnEnter() doesn't seem to work with ajaxForm -->
	<form id="searchForm" name="searchForm" method="GET">
		{% csrf_token %} <!-- Even though this is currently a GET, include anyway for if we switch -->
		<input type="text" name="searchString" value=""/>
		<input type="submit" name="method" value="Search" onclick="searchFiles();return false;"/>
	</form>

	<table id="filesTable" name="filesTable" class='sortable'>
		<tr><th></th><th></th><th></th><th>Start Time</th><th>Alias<!-- [Relative Path]--></th><th>Sensor</th><th>Duration (s)</th></tr>
	</table>


{% endblock content %}

templates/tools/createUser.html
{% extends "tools/base.html" %}
{% block content %}
{% load crispy_forms_tags %}

{% include 'tools/adminMenu.html' %}

<div class="col-md-9">

  <div class="panel panel-primary start-new-library">
    <div class="panel-heading">Create User</div>
    <div class="panel-body">

      {% if message %}
      <div class="well">
        {{message}}
      </div>
      {% endif %}

      <form action="" id="createUserForm" method="POST">
      	{% csrf_token %}
        {{ form|crispy }}
      	<input class="btn" type="submit" name="method" value="Create User" />
      </form>

    </div>
  </div>
</div>
{% endblock content %}

templates/tools/info.html
<link rel="stylesheet" href="{{ArloUrlPrefix}}/site_media/css/global.css" type="text/css" />

<H1>{{heading}}</H1>
<HR>
<p>{{content}}</p>

templates/tools/searchForm.html
<form method="GET" action="{{ArloUrlPrefix}}/tools/searchAudioFileNames">
  <div class="input-group">
    <input type="text" name="searchString" class="form-control" placeholder="{{ searchPrompt}}" />
    {% if currentProjectId %}
      <input type="hidden" name="projectId" value= {{ currentProjectId }} />
    {% elif currentLibraryId %}
      <input type="hidden" name="libraryId" value= {{ currentLibraryId }} />
    {% endif %}
    <span class="input-group-btn">
      <input class="btn btn-secondary" type="submit" value="Go!" />
    </span>
  </div>
</form>

templates/tools/startNewLibrary.html
{% extends "tools/base.html" %}

{% block content %}
{% load crispy_forms_tags %}

<div class="col-md-12">

  <div class="panel panel-primary start-new-library">
    <div class="panel-heading">Start New Library</div>
    <div class="panel-body">
      <form action="startNewLibrary" method="POST">
      	{% csrf_token %}
      	{{ form|crispy }}
      	<input type="submit" value="Submit" />
      </form>
    </div>
  </div>
  
</div><!-- .col-md-12 -->

{% endblock content %}

templates/tools/transcript.html
{% extends "tools/base.html" %}
{% block javascript%}

{% load staticfiles %}

<script src="{% static 'tools/js/arlo.js' %}" type="text/javascript"></script>

<script type="text/javascript">
<!--
	$(document).ready(function(){

		SetupHelpButtons('{{ArloUrlPrefix}}');

	});
-->
</script>
{% endblock javascript %}
{% block content %}

<form action="" name ="transcript"method ="POST">
	{% csrf_token %}
	<p>Num Frequency Bands:{{form.numFrequencyBands}}<img src="{% static 'tools/img/info.gif' %}" class="help" height="12px" width="12px" id="frequencyBands"/></p>
	{{form.numTimeFramesPerSecond.errors}}
	<p>Num Time Frames Per Second:{{form.numTimeFramesPerSecond}}<img src="{% static 'tools/img/info.gif' %}" class="help" height="12px" width="12px" id="framesPerSecond"/></p>
	{{form.dampingRatio.errors}}
	<p>Damping Ratio:{{form.dampingRatio}}<img src="{% static 'tools/img/info.gif' %}" class="help" height="12px" width="12px" id="dampingRatio"/></p>
	{{form.minFrequency.errors}}
	<p>Min Frequency:{{form.minFrequency}}<img src="{% static 'tools/img/info.gif' %}" class="help" height="12px" width="12px" id="minFrequency"/></p>
	{{form.maxFrequency.errors}}
	<p>Max Frequency:{{form.maxFrequency}}<img src="{% static 'tools/img/info.gif' %}" class="help" height="12px" width="12px" id="maxFrequency"/></p>
	{{form.spectraWeight.errors}}
	<p>Spectra Weight:{{form.spectraWeight}}<img src="{% static 'tools/img/info.gif' %}" class="help" height="12px" width="12px" id="spectraWeight"/></p>
	{{form.pitchWeight.errors}}
	<p>Pitch Weight:{{form.pitchWeight}}<img src="{% static 'tools/img/info.gif' %}" class="help" height="12px" width="12px" id="pitchWeight"/></p>
	{{form.pitchEnergyWeight.errors}}
	<p>Pitch Energy Weight:{{form.pitchEnergyWeight}}<img src="{% static 'tools/img/info.gif' %}" class="help" height="12px" width="12px" id="pitchEnergyWeight"/></p>
	{{form.averageEnergyWeight.errors}}
	<p>Average Energy Weight:{{form.averageEnergyWeight}}<img src="{% static 'tools/img/info.gif' %}" class="help" height="12px" width="12px" id="averageEnergyWeight"/></p>
	{{form.numRandomProbes.errors}}
	<p>Num Random Probes:{{form.numRandomProbes}}<img src="{% static 'tools/img/info.gif' %}" class="help" height="12px" width="12px" id="numRandomProbes"/></p>
	{{form.minPerformance.errors}}
	<p>Min Match Performance:{{form.minPerformance}}<img src="{% static 'tools/img/info.gif' %}" class="help" height="12px" width="12px" id="minPerformance"/></p>
	<input type="submit"/>
</form>
{% endblock content %}

templates/tools/uploadAudioFile.html
{% extends "tools/base.html" %}

{% block javascript %}

<script type="text/javascript">

$(document).ready(function(){

  {% if defaultLibrary %}
    $('select#id_library option[value="' + {{defaultLibrary}} + '"]').prop("selected",true);
  {% endif %}

  {% if defaultProject %}
    $('select#id_project option[value="' + {{defaultProject}} + '"]').prop("selected",true);
  {% endif %}

})

</script>

{% endblock javascript %}



{% block content %}
{% load crispy_forms_tags %}

<div class="col-md-12">

  <div class="panel panel-primary start-new-library">
    <div class="panel-heading">Upload Media File</div>
    <div class="panel-body">
      <form action="uploadAudioFile" method="POST" enctype="multipart/form-data">
      	{% csrf_token %}
      	{{ form|crispy }}
      	<input type="submit" value="Submit" />
      </form>
    </div>
  </div>

</div><!-- .col-md-12 -->

{% endblock content %}