metatagging/urls.py
from django.conf.urls import url
from django.http import HttpResponseRedirect

from views import chooseProject, chooseTagSet, chooseMetaTaggingForm, metaTaggingOverview, classifyTag, exportClassifications, visualizeClassifications

urlpatterns = [

  url(r'^$', lambda x: HttpResponseRedirect('chooseProject')),

  url(r'^chooseProject$', 
        chooseProject.chooseProject),

  url(r'^chooseTagSet/(?P<projectId>\d+)$', 
        chooseTagSet.chooseTagSet, 
        name='chooseTagSet'),

  url(r'^chooseMetaTaggingForm/(?P<projectId>\d+)/(?P<tagSetId>\d+)$', 
        chooseMetaTaggingForm.chooseMetaTaggingForm, 
        name='chooseMetaTaggingForm'),

  url(r'^metaTaggingOverview/(?P<projectId>\d+)/(?P<tagSetId>\d+)/(?P<tagMetaFormId>\d+)$', 
        metaTaggingOverview.metaTaggingOverview, 
        name='metaTaggingOverview'),

  url(r'^classifyTag/(?P<projectId>\d+)/(?P<tagSetId>\d+)/(?P<tagMetaFormId>\d+)/(?P<tagIndex>\d+)$', 
        classifyTag.classifyTag, 
        name='classifyTag'),

  url(r'^exportUserClassifications/(?P<projectId>\d+)/(?P<tagSetId>\d+)/(?P<tagMetaFormId>\d+)$', 
        exportClassifications.exportClassifications, 
        {'requestUserOnly':True}, 
        name='exportUserClassifications'),

  url(r'^exportAllClassifications/(?P<projectId>\d+)/(?P<tagSetId>\d+)/(?P<tagMetaFormId>\d+)$', 
        exportClassifications.exportClassifications, 
        {'requestUserOnly':False}, 
        name='exportAllClassifications'),

  url(r'^visualizeAllClassifications/(?P<projectId>\d+)/(?P<tagSetId>\d+)/(?P<tagMetaFormId>\d+)$', 
        visualizeClassifications.visualizeAllClassifications, 
        name='visualizeAllClassifications'),
    
]

urls.py
from django.conf.urls import *
from django.contrib import admin, auth
from django.contrib.auth import views as auth_views
from django.views import static
from django.conf import settings
import rest_framework.authtoken.views as rest_views

from tools import urls as tools_urls
from tools.views import index
from poetrytagging import urls as poetrytagging_urls
from metatagging import urls as metatagging_urls
from api import urls as api_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/login/$', auth_views.login),

    url(r'^tools/', include(tools_urls)),
    url(r'^poetrytagging/', include(poetrytagging_urls)),
    url(r'^metatagging/', include(metatagging_urls)),

    url(r'^$', index.index),

    url(r'^api/', include(api_urls)),
    url(r'^api-token-auth/', rest_views.obtain_auth_token),

    url(r'^changePassword$', auth.views.password_change, name='password_change'),
    url(r'^changePasswordDone$', auth.views.password_change_done, name='password_change_done'),
]

if settings.USE_STATIC_SERVE:
  urlpatterns += [
      url(r'^site_media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes':True}),
      url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes':True}),
  ]

metatagging/views/chooseMetaTaggingForm.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotAllowed
from django.shortcuts import render, redirect
from django import forms
from django.conf import settings

from metatagging.models import TagMetaForm


class ChooseMetaTaggingFormForm(forms.Form):
  metaTaggingForm = forms.ModelChoiceField(TagMetaForm.objects.all().order_by("name"), required=True)

## Select a TagSet to use for the Poetry Tagging
# @param request The Django HTTP request object.
# @param projectId The Database Id of the selected Project.
# @param tagSetId The Database Id of the selected TagSet.
# @return Django HTTP response object.

@login_required
def chooseMetaTaggingForm(request, projectId, tagSetId):
  user = request.user

  if request.method == 'GET':
    form = ChooseMetaTaggingFormForm()

    return render(request, 'chooseMetaTaggingForm.html', {
      'apacheRoot':settings.APACHE_ROOT,
      'user':user,
      'form':form,
      })

  elif request.method == 'POST':
    form = ChooseMetaTaggingFormForm(request.POST)

    if not form.is_valid():
      return render(request, 'chooseMetaTaggingForm.html', {
        'apacheRoot':settings.APACHE_ROOT,
        'user':user,
        'form':form,
        })

    data = form.cleaned_data
    metaTaggingForm = data['metaTaggingForm']

    return redirect('metaTaggingOverview', projectId=projectId, tagSetId=tagSetId, tagMetaFormId=metaTaggingForm.id)


  else:
    return HttpResponseNotAllowed(['GET', 'POST'])

metatagging/views/chooseProject.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotAllowed
from django.shortcuts import render, redirect
from django import forms
from django.conf import settings

from tools.models import Project


class ChooseProjectForm(forms.Form):
  project = forms.ModelChoiceField(Project.objects.none(), required=True)

## Select a Project to use for the Poetry Tagging
# @param request The Django HTTP request object.
# @return Django HTTP response object.

@login_required
def chooseProject(request):
  user = request.user

  if request.method == 'GET':
    form = ChooseProjectForm()
    form.fields['project'] = forms.ModelChoiceField(Project.objects.getUserProjects(user).order_by('name'), required=True)

    return render(request, 'chooseProject.html', {
      'apacheRoot':settings.APACHE_ROOT,
      'user':user,
      'form':form,
      })


  elif request.method == 'POST':
    form = ChooseProjectForm(request.POST)
    form.fields['project'] = forms.ModelChoiceField(Project.objects.getUserProjects(user).order_by('name'), required=True)

    if not form.is_valid():
      return render(request, 'chooseProject.html', {
        'apacheRoot':settings.APACHE_ROOT,
        'user':user,
        'form':form,
        })

    data = form.cleaned_data
    project = data['project']

    return redirect('chooseTagSet', projectId=project.id)

  else:
    return HttpResponseNotAllowed(['GET', 'POST'])

metatagging/views/chooseTagSet.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotAllowed
from django.shortcuts import render, redirect
from django import forms
from django.conf import settings

from tools.models import Project, TagSet


class ChooseTagSetForm(forms.Form):
  tagSet = forms.ModelChoiceField(TagSet.objects.none(), required=True)

## Select a TagSet to use for the Poetry Tagging
# @param request The Django HTTP request object.
# @param projectId The Database Id of the selected Project.
# @return Django HTTP response object.

@login_required
def chooseTagSet(request, projectId):
  user = request.user
  project = Project.objects.get(id=projectId)

  if request.method == 'GET':
    form = ChooseTagSetForm()
    form.fields['tagSet'] = forms.ModelChoiceField(TagSet.objects.filter(project=project).order_by('name'), required=True)

    return render(request, 'chooseTagSet.html', {
      'apacheRoot':settings.APACHE_ROOT,
      'user':user,
      'form':form,
      })

  elif request.method == 'POST':
    form = ChooseTagSetForm(request.POST)
    form.fields['tagSet'] = forms.ModelChoiceField(TagSet.objects.filter(project=project).order_by('name'), required=True)

    if not form.is_valid():
      return render(request, 'chooseTagSet.html', {
        'apacheRoot':settings.APACHE_ROOT,
        'user':user,
        'form':form,
        })

    data = form.cleaned_data
    tagSet = data['tagSet']

    return redirect('chooseMetaTaggingForm', projectId=project.id, tagSetId=tagSet.id)


  else:
    return HttpResponseNotAllowed(['GET', 'POST'])

tools/views/catalog.py
import contextlib
import logging
import time
import timeit

from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponseForbidden
from django.db.models import Q
from django import forms
from django.conf import settings

from tools.models import UserSettings, Project, Tag, TagClass, TagSet, RenameTagClassForm
from .userPermissions import ARLO_PERMS
from .project import getTagSetTagClasses
from .spectra import generateSpectraImage


class CatalogForm(forms.Form):
  gain = forms.FloatField('gain', initial=1.0)
  numFramesPerSecond = forms.FloatField('numFramesPerSecond', initial=25.0)
  numFrequencyBands = forms.IntegerField('numFrequencyBands', initial=64)
  spectraDampingFactor = forms.FloatField('spectraDampingFactor', initial=0.02)

  tagsPerPage = forms.IntegerField(label='userTagsPerPage', initial=20)
  tagPageNumber = forms.IntegerField(label='userTagPageNumber', initial=1)

  haveClassesChanged = forms.IntegerField(label='haveClassesChanged', initial=0, widget=forms.HiddenInput, required=False)
  sortBy = forms.ChoiceField(label='sortBy',
    choices=[('strengthDown', 'Strength(Descending)'),
             ('strengthUp', 'Strength(Ascending)'),
             ('cron', 'Chronological Order'),
             ('realTime', 'Real Time')])

  showUserTags = forms.BooleanField(label='Show User Tags', required=False, initial=True)
  showMachineTags = forms.BooleanField(label='Show Machine Tags', required=False, initial=True)
  discoveryMode = forms.IntegerField(label='Discovery Mode', initial=0, widget=forms.HiddenInput, required=False)

  tagSets    = forms.ModelMultipleChoiceField(TagSet.objects.none(), widget=forms.CheckboxSelectMultiple, required=True)
  tagClasses = forms.ModelMultipleChoiceField(TagClass.objects.none(), widget=forms.CheckboxSelectMultiple, required=True)



## Web interface to display a 'catalog' of tags. A GET will will display the
# CatalogForm, and the subsequent POST will retrieve the data.
# @param request The Django HTTP request object
# @param projectId The database ID of the Project.
# @return Django HTTP response object

@login_required
def catalog(request, projectId):

  user = request.user
  logging.info("Retrieving Catalog: user = " + user.__str__() + " projectId = " + projectId.__str__())
  userSettings = UserSettings.objects.get(user=user, name='default')
  project = Project.objects.get(id=projectId)

  # Check Permissions
  if not project.userHasPermissions(user, ARLO_PERMS.READ):
    return HttpResponseForbidden("Forbidden")

  ###
  # tagClassList is our main return dataset
  # this is a list of Tuples
  #   [ (tagClassId, tagClassName, tags), ]
  #   tagClassId int
  #   tagClassName string
  #   tags - A list of dictionaries
  #     {
  #        'id':,
  #        'displayName':,
  #        'userTagged':,
  #        'machineTagged':,
  #        'imagePath':,
  #      }
  tagClassList = []

  tagClassIDList = []


  if request.method == 'POST': # If the form has been submitted...

    form = CatalogForm(request.POST) # A read-only form bound to the POST data

    # Select Form Fields
    form.fields['tagSets'] = forms.ModelMultipleChoiceField(project.getTagSets(include_hidden=False), required=True, widget=forms.SelectMultiple(attrs={'size':11}))
    form.fields['tagClasses'] = forms.ModelMultipleChoiceField(project.getTagClasses(), required=True, widget=forms.SelectMultiple(attrs={'size':19}))

    if form.is_valid(): # if all validation rules passed

      #######################
      # Settings

      # data converted to list, not passed back
      # data[] only used in the settings section, newData contains modified values
      data = form.cleaned_data

      gain = data['gain']
      spectraDampingFactor = data['spectraDampingFactor']
      numFramesPerSecond = data['numFramesPerSecond']
      numFrequencyBands = data['numFrequencyBands']
      sortBy = data['sortBy']
      tagsPerPage = data['tagsPerPage']

      ##
      # Navigation

      method = data.get('method')
      showUserTags = data.get('showUserTags', False)
      showMachineTags = data.get('showMachineTags', False)

      tagPageNumber = data['tagPageNumber']
      if data['haveClassesChanged'] == 0:  # this is updated by JavaScript
        if method == 'nextPage':
          tagPageNumber += 1
        if method == 'previousPage':
          if (data['tagPageNumber'] - 1) > 0:
            tagPageNumber -= 1

      else:
        tagPageNumber = 1


      # static spectra settings
      spectraBorderWidth = 0
      spectraTopBorderHeight = 0
      timeScaleHeight = 0

      ##
      # Get Selected Libraries, TagSets, and TagClasses

      selectedTagSets = data['tagSets']
      selectedTagClasses = data['tagClasses']


      ##
      # debug logging settings

      logging.debug("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^")
      logging.debug("Catalog Form Post Data: " + str(data))
      logging.debug("Method:                 " + method.__str__())
      logging.debug("showUserTags:           " + showUserTags.__str__())
      logging.debug("showUserTags:           " + showUserTags.__str__())
      logging.debug("HaveClassesChanged:     " + data['haveClassesChanged'].__str__())
      logging.debug("tagPageNum:             " + tagPageNumber.__str__())
      logging.debug("tagsPerPage:            " + tagsPerPage.__str__())
      logging.debug("Gain:                   " + gain.__str__())
      logging.debug("spectraDampingFactor:   " + spectraDampingFactor.__str__())
      logging.debug("numFramesPerSecond:     " + numFramesPerSecond.__str__())
      logging.debug("numFrequencyBands:      " + numFrequencyBands.__str__())
      logging.debug('sortBy:                 ' + sortBy.__str__())
      logging.debug('TagSets:                ' + selectedTagSets.__str__())
      logging.debug('TagClasses:             ' + selectedTagClasses.__str__())

      #############################
      # Main loop to retrieve tags

      # FYI, this loop goes pretty much to the end...
      for tagClass in selectedTagClasses:

        tagClassIDList.append(tagClass.id)


        ###
        # Get Tags

        # NOTE the use of the select_related to also pull in the
        # mediaFile object. Optimization for the sort function
        with timed_execution("Querying Tags - {}".format(tagClass.className)):
          tags = Tag.objects.select_related('mediaFile').filter(
                                  tagClass=tagClass,
                                  tagSet__in=selectedTagSets,
                                  )
        # userTag / machineTag logic
        # Have to use Q to build an ORing query for logic to satisfy showUserTags
        # and showMachineTags fields in catalog form. Tried doing this with Q() in
        # the above query, but didn't get it working, and went the easy route
        if showUserTags and showMachineTags:
          tags = tags.filter(Q(userTagged=True) | Q(machineTagged=True))
        else:
          if showUserTags:
            tags = tags.filter(userTagged=True)
          elif showMachineTags:
            tags = tags.filter(machineTagged=True)
          else: # Guess we don't want any tags...
            tags = Tag.objects.none()

        ###
        # Sort Tags

        # NOTE - Possible Performance Issue - To compute an accurate page number /
        # position, we basically have to sort all tags first, then select the ones
        # for display. This may get out of hand for some projects

        # NOTE that this returns a regular list, not a querySet
        # change querysets into list to simplify manipulation later(in template)
        with timed_execution("Sort Tags"):
          tags = sortTags(tags, sortBy)


        ###
        # compute Tag Range / Page Numbers

        with timed_execution("Compute Tag Range / Page Numbers - {}".format(tagClass.className)):
          numTags = len(tags)
          logging.debug('Number of tags: ' + str(numTags))
          startTagIndex = tagsPerPage * (tagPageNumber - 1)
          endTagIndex = startTagIndex + tagsPerPage
          if numTags > 0:
            if startTagIndex >= 0 and endTagIndex <= numTags:
              tags = tags[startTagIndex:endTagIndex]
            elif startTagIndex < numTags and startTagIndex >= 0 and endTagIndex > numTags:
              tags = tags[startTagIndex:]
            else:
              tags = Tag.objects.none()
          else:
            tags = Tag.objects.none()

        logging.info("tagRange: " + startTagIndex.__str__() + " to " + endTagIndex.__str__())


        ###
        # Build Tag data return list for this class

        tagInfoList = []
        with timed_execution("Build Tag Spectras / Info - {}".format(tagClass.className)):
          for tag in tags:

            ###
            #  Build Spectra

            spectra_params = {
              'userSettings':userSettings,
              'audioFile': tag.mediaFile,

              'startTime': tag.startTime,
              'endTime': tag.endTime,
              'gain': gain,
              'numFramesPerSecond': numFramesPerSecond,
              'numFrequencyBands':numFrequencyBands,
              'dampingFactor':spectraDampingFactor,

              'minFrequency':userSettings.catalogViewSpectraMinimumBandFrequency,
              'maxFrequency':userSettings.catalogViewSpectraMaximumBandFrequency,

              'simpleNormalization':True,
              'showTimeScale':False,
              'showFrequencyScale':False,
              'borderWidth':spectraBorderWidth,
              'topBorderHeight':spectraTopBorderHeight,
              'timeScaleHeight':timeScaleHeight,
              'catalogSpectraNumFrequencyBands':numFrequencyBands}

            (success, imageFilePath, audioSegmentFilePath) = generateSpectraImage(**spectra_params)
            if not success:
              logging.error("CATALOG - Error While Generating Spectra for TagID: " + tag.id.__str__())


            # Add to list

metatagging/templates/chooseMetaTaggingForm.html
{% extends "tools/base.html" %}
{% block javascript %}

	{% load staticfiles %}

	<link rel="stylesheet" href="{% static 'tools/css/arlo.css' %}" type="text/css" />
{% endblock javascript %}

{% block content %}

<H1>Select Meta-Tagging Form</H1>

<form method="POST">
	{% csrf_token %}
	<p>
		{{form.as_p}} 
	</p>
	<input type='submit' />
</form>

{% endblock content %}

metatagging/templates/chooseProject.html
{% extends "tools/base.html" %}
{% block javascript %}
	{% load staticfiles %}

	<link rel="stylesheet" href="{% static 'tools/css/arlo.css' %}" type="text/css" />
{% endblock javascript %}

{% block content %}

<H1>Select Project</H1>

<form method="POST">
	{% csrf_token %}
	<p>
		{{form.as_p}} 
	</p>
	<input type='submit' />
</form>

{% endblock content %}

metatagging/templates/chooseTagSet.html
{% extends "tools/base.html" %}
{% block javascript %}

	{% load staticfiles %}

	<link rel="stylesheet" href="{% static 'tools/css/arlo.css' %}" type="text/css" />
{% endblock javascript %}

{% block content %}

<H1>Select TagSet</H1>

<form method="POST">
	{% csrf_token %}
	<p>
		{{form.as_p}} 
	</p>
	<input type='submit' />
</form>

{% endblock content %}

metatagging/templates/classifyTag.html
{% extends "tools/base.html" %}

{% block javascript %}

{% load static %}

<link rel="stylesheet" href="{% static 'third-party/jQuery-contextMenu/jquery.contextMenu.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'admin/css/base.css' %}" type="text/css"/>
<link rel="stylesheet" href="{% static 'tools/css/visualizeProjectFile.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'tools/css/arlo.css' %}" type="text/css" />

<script src="{% static 'third-party/jQuery-contextMenu/jquery.ui.position.js' %}" type="text/javascript"></script>
<script src="{% static 'third-party/jQuery-contextMenu/jquery.contextMenu.js' %}" type="text/javascript"></script>
<script src="{% static 'tools/js/audioPlayer.js' %}" type="text/javascript"></script>
<script src="{% static 'tools/js/arlo.js' %}" type="text/javascript"></script>

<script type="text/javascript">
<!--
	//variables passed in through django
	var ArloStaticUrl = "{% get_static_prefix %}";
	var audioID = "{{audioID}}";
	var currentTagID;

	var projectId = '{{tag.tagSet.project.id}}';

	var urlPrefix = "{{ArloUrlPrefix}}";
	var mediaUrl = "{% get_media_prefix %}";

	var tagSetName = "{{tagSet.name}}";

	var audioPlayer;

	var LOADING_GIF_URL = "{% static 'tools/img/loading.gif' %}";
	var EMPTY_WAV_URL = "{% static 'tools/empty.wav' %}";
-->
</script>

<script src="{% static 'tools/js/spectra.js' %}" type="text/javascript"></script>
<script src="{% static 'tools/js/tag.js' %}" type="text/javascript"></script>


<script type ="text/javascript">
<!--
	$(document).ready(function(){

		ARLOInit(); /* Setup ARLO Global Utilities */

		/*  Replaced by Custom Handlers Below */
		/* $("#spectraForm").ajaxForm({
			url:'{{ArloUrlPrefix}}/tools/createAudioSpectra',
			dataType:'json',
			success:spectraFormCallback
		});
		*/

		/* Event Handler for Form Submit */
		$("#staticSettingsForm :submit").click(OnSubmitSettingsForm);

		audioPlayer = new AudioPlayer(
			'audioPlayerid', 
			"{% static 'tools/empty.wav' %}", 
			document.getElementById("audioSegmentDiv")
		);

		/* Event Handler to Show/Hide Spectra Form */
		$("#spectraFormHeader").click(function() {
			$("#staticSettingsForm").toggle(100);
		});

		LoadSettingsFormLastData();
		getSpectra();
	});


	/* ***************************************************** */
	/*                                                       */
	/*          Settings Form Save / Load Settin;gs           */
	/*                                                       */
	/* ***************************************************** */

	function OnSubmitSettingsForm(event) {

		SaveSettingsFormLastData();

		getSpectra();

		return false;  /* return false to stop event propagation (and form submission outside AJAX) */
	};

	function SaveSettingsFormLastData() {
		ARLOSettingSet("MetaTaggingLastLoadAudio", ( $("#id_loadAudio").is(':checked') ? "1" : "0"));

		ARLOSettingSet("MetaTaggingLastSpectraNumFramesPerSecond", $("#id_spectraNumFramesPerSecond").val());
		ARLOSettingSet("MetaTaggingLastSpectraNumFrequencyBands", $("#id_spectraNumFrequencyBands").val());
		ARLOSettingSet("MetaTaggingLastSpectraDampingFactor", $("#id_spectraDampingFactor").val());

		ARLOSettingSet("MetaTaggingLastSpectraGain", $("#id_gain").val());
		ARLOSettingSet("MetaTaggingLastSpectraMinimumBandFrequency", $("#id_spectraMinimumBandFrequency").val());
		ARLOSettingSet("MetaTaggingLastSpectraMaximumBandFrequency", $("#id_spectraMaximumBandFrequency").val());
		ARLOSettingSet("MetaTaggingLastContextWindow", $("#id_contextWindow").val());
	};

	function LoadSettingsFormLastData() {
		var s;

		s = ARLOSettingGet("MetaTaggingLastLoadAudio");
		if (s) { 
			if (s == "1") {
				$("#id_loadAudio").prop('checked', true);
			} else {
				$("#id_loadAudio").prop('checked', false);
			}
		}

		s = ARLOSettingGet("MetaTaggingLastSpectraNumFramesPerSecond");
		if (s) { $("#id_spectraNumFramesPerSecond").val(s); }
		s = ARLOSettingGet("MetaTaggingLastSpectraNumFrequencyBands");
		if (s) { $("#id_spectraNumFrequencyBands").val(s); }
		s = ARLOSettingGet("MetaTaggingLastSpectraDampingFactor");
		if (s) { $("#id_spectraDampingFactor").val(s); }
		
		s = ARLOSettingGet("MetaTaggingLastSpectraGain");
		if (s) { $("#id_gain").val(s); }
		s = ARLOSettingGet("MetaTaggingLastSpectraMinimumBandFrequency");
		if (s) { $("#id_spectraMinimumBandFrequency").val(s); }
		s = ARLOSettingGet("MetaTaggingLastSpectraMaximumBandFrequency");
		if (s) { $("#id_spectraMaximumBandFrequency").val(s); }
		s = ARLOSettingGet("MetaTaggingLastContextWindow");
		if (s) { $("#id_contextWindow").val(s); }

	};



-->
</script>

{% endblock javascript %}



{% block content %}

<H1>Classify Tag</H1>

<p>Tag Example Id: {{tag.id}}</p>

<hr>


<!--                                         -->
<!--             Spectra Image               -->
<!--                                         -->


<div id=audioSegmentDiv>
</div>

<a href="{{urlPrefix}}/site_media/{{audioSegmentFilePath}}" id="audioSegmentDownload">Right-Click Here to Download Audio File</a><br/>

<div id="spectraStatusDiv"></div>

<div id="image" style="position:relative"></div>
<br/>

<!-- Navigation Links -->
{% if prevUrl %}
	<a href='{{prevUrl}}'>Prev Window</a>
{% else %}
	Prev Window
{% endif %}
	||
{% if nextUrl %}
	<a href='{{nextUrl}}'>Next Window</a>
{% else %}
	Next Window
{% endif %}

<!--                                         -->
<!--        Categorization Form              -->
<!--                                         -->

<!-- This is custom user-supplied data -->

{{tagMetaFormTemplateData|safe}}


<!--                                         -->
<!--       Spectra Settings Form             -->
<!--                                         -->

<br />
<br />
<table>
	<h3 id="spectraFormHeader">Spectra Settings (Click to Show / Hide)</h3>
	<div id="staticSettingsForm" hidden='true'>
		<form action="" id="spectraForm" method="POST" onkeypress="return SubmitFormOnEnter(event)">
			{% csrf_token %}
			{{spectraForm.as_p}}
			<input type="submit" name="method" value="Submit" />
		</form>
	</div>
</table>


{% endblock content %}

metatagging/templates/metaTaggingOverview.html
{% extends "tools/base.html" %}
{% block javascript %}
	{% load staticfiles %}

	<link rel="stylesheet" href="{% static 'tools/css/arlo.css' %}" type="text/css" />
{% endblock javascript %}

{% block content %}

<H1>Overview of MetaTagging</H1>

<p>{{ numClassifiedTags }} of {{numTags}} Tags already Classified.</p>

<table><tr><td>
	<form action='' method="POST">
		{% csrf_token %}
		<input type='submit' value="Start at Beginning"/>
	</form>
</td><td>
&nbsp;
</td><td>
	{% if firstUntaggedIndex != None %}
		<form action='' method="POST">
			{% csrf_token %}
			<input type='hidden' name='gotoIndex' value='{{ firstUntaggedIndex }}'>
			<input type='submit' value="Jump to First Untagged"/>
		</form>
	{% endif %}
</td></tr></table>

<br />
<a href="{{ exportUserClassificationsUrl }}">Export My Tag Classifications</a>
<br />
<br />
<a href="{{ exportAllClassificationsUrl }}">Export All Tag Classifications</a>
<br />
<br />
<a href="{{ visualizeAllClassificationsUrl }}">Visualize All Tag Classifications</a>
<br />
<br />
<br />
<h4>Documentation</h4>
<a href="http://wiki.arloproject.com/index.php?title=MetaTagging">http://wiki.arloproject.com/index.php?title=MetaTagging</a>

{% endblock content %}